# Paramter for simulated annealing
STEP_SIZE = 0.1
MAX_ITER = 5000
MAX_TEMP = 2000
TEMP_COEFF = 0.999
EPS = 1e-3

# Adaptive simulated annealing
NUM_CYCLES_STEP = 10
NUM_CYCLES_TEMP = 100
NUM_CYCLES_EPS = 4
EPS_THRESH = 0.01
MAX_STEP_SIZE = 0.1

# Parameter for utils
SAFE_MARGIN_COLLISION = 0.01
MARGIN_COLLISION = 1e-6
WEIGHT_SINGLE_STABILITY = 10.0
WEIGHT_COLLISION = 1.0
WEIGHT_TOTAL_STABILITY = 1.0
WEIGHT_COMPACT = 1.5
WEIGHT_ORTHOGONALITY = 2.0
SINGLE_STABILITY_MARGIN = 0.0
