url:
  master: tcp://127.0.0.1:12345
  recv: tcp://127.0.0.1:12346
  send: tcp://127.0.0.1:12347

log_dir: log/llm_planner

prompt_path:
  categorize: prompt/categorize.json
  group_place: prompt/group_place.json
  place: prompt/place.json
  preference: prompt/preference.json

model:
  name: GPT-3.5  # or GPT-3.5 Turbo used in the paper
  api_key: <API_KEY>  # replace with your api key here
  url: http://127.0.0.1:60000/chat/completions  # the url of your local LLM API server
  max_trial: 3

max_context: 10000
